// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com.br/gibranct/ride/internal/payment/application/usecase"
)

// Injectors from wire.go:

func NewProcessPayment() *usecase.ProcessPayment {
	processPayment := usecase.NewProcessPaymentUseCase()
	return processPayment
}
